### ISSUE TITLE
Wrong screen lock date 

### ISSUE THREAD

**Issue by TheKerevas** [BIOLorenz/Xiaomi.eu-MIUI_v13-Italian#1]
The latest Weekly in the Italian language,  displays the date in mm / dd instead of dd / mm on the lock screen.

![photo_2022-03-12_15-58-59](https://user-images.githubusercontent.com/101466273/158023096-f8ae054a-6d59-44a2-88e3-2bb1a42347b5.jpg)

**Comment by BIOLorenz** [comment]
Ciao, 
il problema dovrebbe essere stato fixato.
