### ISSUE TITLE
Orologio Lockscreen

### ISSUE THREAD

**Issue by noisystyle** [BIOLorenz/Xiaomi.eu-MIUI_v13-Italian#13]
![1000012246](https://user-images.githubusercontent.com/9551169/210134949-1d4296ec-d39a-42bc-ab80-90d3ca8a5c37.jpg)

Il giorno nell'orologio della lockscreen viene anticipato dalla scritta "tigre"

**Comment by BIOLorenz** [comment]
Il bug dovrebbe essere fixato nelle prossime release.
Si prega di seguire la nuova repo https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian per le ultime traduzioni
