### ISSUE TITLE
Schermata di blocco

### ISSUE THREAD

**Issue by zeidof** [BIOLorenz/Xiaomi.eu-MIUI_v13-Italian#14]
Il giorno nell'orologio della lockscreen viene anticipato dalla scritta "tigre"
![photo_2023-01-07_00-59-56](https://user-images.githubusercontent.com/122131943/211119226-f72ba1d5-7307-4831-857a-c745e51d8ea3.jpg)

**Comment by BIOLorenz** [comment]
Il bug dovrebbe essere fixato nelle prossime release.
Si prega di seguire la nuova repo https://github.com/BIOLorenz/Xiaomi.eu-MIUI_v14-Italian per le ultime traduzioni
