### ISSUE TITLE
Errore di rete su ultime versioni app

### ISSUE THREAD

**Issue by Ale-83** [BIOLorenz/Xiaomi.eu-MIUI_v13-Italian#3]
Ciao,  non so se devo segnalare qui ma ho riscontrato questo errore, ho provato ad aggiornare, tramite apk le app di Xiaomi come theme e app vault naturalmente con l'ultima versione CN solo che sono inutilizzabili perché da un errore di rete e non visualizza nulla. 
Mentre se vado a sovrascriverle con le app versione global, queste ultime non danno problemi.

**Comment by BIOLorenz** [comment]
Ciao,
il problema va segnalato sul forum di Xiaomi.eu, questa sezione è dedicata esclusivamente alle traduzioni :)
