### ISSUE TITLE
Traduzioni app Galleria

### ISSUE THREAD

**Issue by M4th12** [BIOLorenz/Xiaomi.eu-MIUI_v13-Italian#5]
1)![IMG_20220426_111256](https://user-images.githubusercontent.com/89078127/165319895-95c4b36f-ad1d-4be2-9eaa-678bd6828b01.jpg)

2)![IMG_20220426_110646](https://user-images.githubusercontent.com/89078127/165319892-f03b3265-3cfd-49aa-badc-55e2e37c3c63.jpg)

3)![IMG_20220426_110412](https://user-images.githubusercontent.com/89078127/165319887-81d0cdf3-0801-4e48-9c5c-bfb3f3a82a24.jpg)

4)![Screenshot_2022-04-26-10-52-46-786_com miui gallery](https://user-images.githubusercontent.com/89078127/165319927-a05ef33c-c6f6-4880-80f8-c8ab4c6eb299.jpg)

5)![IMG_20220426_105459](https://user-images.githubusercontent.com/89078127/165319875-0e820eb7-7dd5-4d72-9e83-2717dd374ca0.jpg)

6)![Screenshot_2022-04-08-16-16-52-622_com miui gallery](https://user-images.githubusercontent.com/89078127/165319904-27bc6bbf-5378-4510-9289-37d8bbe05122.jpg)

7)![IMG_20220426_105638](https://user-images.githubusercontent.com/89078127/165319880-0987e64e-016a-4fae-bbd3-cbf88fc09083.jpg)

8)![Screenshot_2022-04-26-10-46-01-713_com miui gallery](https://user-images.githubusercontent.com/89078127/165319922-aee3d3a0-2e9e-4bdb-bfcc-b8ee3bee0d95.jpg)

9)![Screenshot_2022-04-08-16-14-54-315_com miui gallery](https://user-images.githubusercontent.com/89078127/165319898-5503d0d3-df40-4578-8a6d-288b0c539ef6.jpg)

10)![Screenshot_2022-04-26-18-19-16-019_com miui gallery](https://user-images.githubusercontent.com/89078127/165347330-17a4e836-0435-44c3-b238-8611e2029004.jpg)

Informazioni:
Dispositivo: Imi (Hmk30Pro)
Versione: 13.0.2 Stabile
Applicazione: Impostazioni
1° Immagine: Galleria>Foto
2° Immagine: Galleria>Album
3° Immagine: Galleria>Album
4° Immagine: Galleria>Scegliere un immagine>Altro
5° Immagine: Galleria>Scegliere un immagine>Modifica>Ritaglia
6° Immagine: Galleria>Scegliere un immagine>Altro>Aggiungi all'album>Scegliere un album
7° Immagine: Galleria>Album>Pulitore
8° Immagine: Galleria>Impostazioni
9° Immagine: Galleria>Impostazioni>Manage permission
10° Immagine:Galleria>Impostazioni>Manage permission>Cliccare su un album non concesso
Suggerimenti: 

1° Immagine:
/8834 foto e 1371 video

2° Immagine:
/I miei album
/Altri album

3° Immagine:
/Tipi di media
/Selfie
/Dinamica
/Organizza le foto

4° Immagine:
/Filigrana protettiva

5° Immagine:
/Personalizzato
/Originale
/Schermo intero

6° Immagine:
/Sposta
/Copia

7° Immagine:
/Mettere la "P" maiscuola alla frase "possono essere liberati"
/Ottimizza lo spazio 
/ Attiva 
/ Attiva la sincronizzazione con il cloud 
/ Libera spazio di archiviazione 
/ Memorizza foto e video originali nel cloud, mantenendo copie piú piccole di alta qualità su questo dispositivo.

8° Immagine:
/Al posto di "Assistente" usare "Ricordi", non c'é nella foto ma e nello stesso menu
/Gestisci permessi

9° Immagine:
/Galleria ha bisogno di permessi per essere in grado di sincronizzare, modificare e gestire gli elementi mostrati di seguito.
/Non concesso
/ 2 album inclusi 
/Concedi
/Concesso
/Concesso (Per Album)

10° Immagine:
/Permessi necessari
/I permessi della galleria sono stati aggiornati. Consenti alla Galleria di accedere a questa cartella per poterne visualizzare il contenuto
/Come concedere i permessi
/Tocca "Avanti" e poi seleziona "Usa questa cartella".
/Annulla /Avanti

**Comment by BIOLorenz** [comment]
Fixed 
d3f4258a811bef98f2fbecacbd4ed9177ab3dcea
936e30890b9ee3156395dc3744cccf3dc21a90d8
aa939cf91130fe93ea00b5acdadba842adbed963
