### ISSUE TITLE
Suggerimenti sezione Schermo attivo

### ISSUE THREAD

**Issue by M4th12** [BIOLorenz/Xiaomi.eu-MIUI_v13-Italian#6]
![Screenshot_2022-04-08-16-32-38-377_com xiaomi misettings](https://user-images.githubusercontent.com/89078127/165352743-ae2da9c4-970c-4aa2-a0db-542b31c0e855.jpg)

Informazioni:
Dispositivo: Imi (Hmk30Pro)
Versione: 13.0.2 Stabile
Applicazione: Impostazioni (Schermo attivo)
1° Immagine: Impostazioni>Schermo attivo

Suggerimenti:
/Al posto di "Cruscotto" usare "Dashboard"
/Nella sezione settimana abbreviare la parola in sett. per evitare sovrapposizioni es. 16° sett.

**Comment by BIOLorenz** [comment]
Fixed 
d3f4258a811bef98f2fbecacbd4ed9177ab3dcea
936e30890b9ee3156395dc3744cccf3dc21a90d8
aa939cf91130fe93ea00b5acdadba842adbed963
