### ISSUE TITLE
Traduzioni app Fotocamera

### ISSUE THREAD

**Issue by M4th12** [BIOLorenz/Xiaomi.eu-MIUI_v13-Italian#7]
1)![Screenshot_2022-04-08-16-13-58-726_com android camera](https://user-images.githubusercontent.com/89078127/165355546-b4482fbe-3bab-4155-9e58-a9fb8c54e3f7.jpg)

2)![Screenshot_2022-04-26-19-16-51-844_com android camera](https://user-images.githubusercontent.com/89078127/165369675-4f192609-8ef1-4690-abb6-c1e1996551bc.jpg)

Informazioni:
Dispositivo: Imi (Hmk30Pro)
Versione: 13.0.2 Stabile
Applicazione: Fotocamera
1° Immagine: Fotocamera>Impostazioni
2° Immagine: Fotocamera>Impostazioni>Preserve settings

Suggerimenti:
1° Immagine:
/Tocca per scattare una foto
/Tocca la schermata di anteprima per scattare una foto
/Mantieni le impostazioni
/Mantieni la modalità precedentemente utilizzata piuttosto che ripristinare automaticamente quella predefinita.
/Avvio automatico
/Rendi Fotocamera più reattiva permettendole di avviarsi automaticamente. Puoi gestire il permesso di avvio automatico nei dettagli dell'app.

2° Immagine:
/Mantieni le impostazioni
/Modalita Fotocamera
/MantienI la modalità usata in precedenza insieme alla selezione della fotocamera anteriore o posteriore
/Bellezza 
/Mantieni le preferenze di Bellezza selezionate durante la sessione precedente
/Fotocamera AI
Mantieni lo stato della Fotocamera AI impostato durante la sessione precedente
/Scatti Dinamici
/Mantieni lo stato di Scatto DinamicI impostato durante la sessione precedente

**Comment by BIOLorenz** [comment]
Fixed 
d3f4258a811bef98f2fbecacbd4ed9177ab3dcea
936e30890b9ee3156395dc3744cccf3dc21a90d8
aa939cf91130fe93ea00b5acdadba842adbed963
