### ISSUE TITLE
Problem now tv

### ISSUE THREAD

**Issue by michelemilan07** [BIOLorenz/Xiaomi.eu-MIUI_v13-Italian#8]
When I open now TV, it gives me an error saying "playback has been interrupted because viewing now through HDMI is not supported" But I have not connected any HDMI cable

**Comment by BIOLorenz** [comment]
Sorry but this section is exclusively for Italian translations.
Please, ask your question in Xiaomi.eu forum.

Cordially
- BIOLorenz

**Comment by michelemilan07** [comment]
Salve, infatti io sto utilizzando la Xiaomi eu italiana, e non riesco ad
utilizzare now TV.
Saluti

Il mar 24 mag 2022, 10:08 Lorenzo ***@***.***> ha scritto:
